spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/user-service}
      auto-index-creation: true

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.web: INFO